# Site settings
title: Asthra Programming Language
email: your-email@example.com
description: >-
  Asthra is a minimal syntax programming language designed with AI
  code generation efficiency and safe C interoperability in mind.
  It is strongly typed with explicit memory management annotations
  and has built-in support for deterministic execution and observability.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://asthra-lang.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom theme name
theme_name: "Saravarsham"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults - automatically apply front matter
defaults:
  # Apply to all files in the docs collection
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "page"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: Blog
    url: /blog/
  - title: GitHub
    url: https://github.com/asthra-lang/asthra

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - .gitignore

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed
  implementation: sass-embedded
  quiet_deps: true

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# SEO settings
author: Asthra Team
twitter:
  username: asthra_lang
social:
  name: Asthra Programming Language
  links:
    - https://github.com/asthra-lang/asthra 

asthra:
  tagline: "AI-native language for code generation"
